networks:
  OOB:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
  net1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/24
  net2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
  net3:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24


services:
  # Host 1 generating sine wave traffic
  host1:
    image: alpine:latest
    platform: linux/arm64
    container_name: sine-lab-host1
    privileged: true
    volumes:
      - ./scripts/host1.sh:/host.sh
    command: sh -c "chmod +x /host.sh && /host.sh"
    restart: unless-stopped
    networks:
      - net2

  # Router 1 - Arista cEOS
  router1:
    image: ceos:${CEOS_VERSION}
    container_name: sine-lab-router1
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    env_file:
      - ./ceos.env
    tmpfs:
      - /mnt/flash
    ports:
      - "2201:22" # SSH
      - "8100:80" # Web Interface
    hostname: router1
    volumes:
      - ./router1/config/startup-config:/mnt/flash/startup-config
    tty: true
    restart: unless-stopped
    command: /sbin/init systemd.setenv=INTFTYPE=eth systemd.setenv=ETBA=1 systemd.setenv=SKIP_ZEROTOUCH_BARRIER_IN_SYSDBINIT=1 systemd.setenv=CEOS=1 systemd.setenv=EOS_PLATFORM=ceoslab systemd.setenv=container=docker
    networks:
      - OOB
      - net1
      - net2

  # Router 2 - Arista cEOS
  router2:
    image: ceos:${CEOS_VERSION}
    container_name: sine-lab-router2
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    env_file:
      - ./ceos.env
    tmpfs:
      - /mnt/flash
    ports:
      - "2202:22" # SSH
      - "8101:80" # Web Interface
    hostname: router2
    volumes:
      - ./router2/config/startup-config:/mnt/flash/startup-config
    tty: true
    restart: unless-stopped
    command: /sbin/init systemd.setenv=INTFTYPE=eth systemd.setenv=ETBA=1 systemd.setenv=SKIP_ZEROTOUCH_BARRIER_IN_SYSDBINIT=1 systemd.setenv=CEOS=1 systemd.setenv=EOS_PLATFORM=ceoslab systemd.setenv=container=docker
    networks:
      - OOB
      - net1
      - net3

  # Host 2 generating offset sine wave traffic
  host2:
    image: alpine:latest
    platform: linux/arm64
    container_name: sine-lab-host2
    privileged: true
    volumes:
      - ./scripts/host2.sh:/host.sh
    command: sh -c "chmod +x /host.sh && /host.sh"
    restart: unless-stopped
    networks:
      - net3
      
  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    platform: linux/arm64
    container_name: sine-lab-grafana
    networks:
      net3:
        ipv4_address: 172.30.0.10
      OOB:
        ipv4_address: 192.168.100.20
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000" # Grafana
    restart: unless-stopped

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    platform: linux/arm64
    container_name: sine-lab-prometheus
    networks:
      net3:
        ipv4_address: 172.30.0.11
      OOB:
        ipv4_address: 192.168.100.21
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090" # Prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    restart: unless-stopped

  # SNMP exporter for network metrics
  snmp-exporter:
    image: prom/snmp-exporter:latest
    platform: linux/arm64
    container_name: sine-lab-snmp-exporter
    networks:
      net3:
        ipv4_address: 172.30.0.12
      OOB:
        ipv4_address: 192.168.100.22
    volumes:
      - ./monitoring/snmp_exporter/snmp.yml:/etc/snmp_exporter/snmp.yml
    ports:
      - "9116:9116" # SNMP Exporter
    restart: unless-stopped

  # Homepage dashboard
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    platform: linux/arm64
    container_name: sine-lab-homepage
    networks:
      net3:
        ipv4_address: 172.30.0.13
      OOB:
        ipv4_address: 192.168.100.23
    volumes:
      - ./monitoring/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro # For Docker integration
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=*
    ports:
      - "3001:3000" # Homepage
    restart: unless-stopped

