global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'snmp_router1'
    static_configs:
      - targets: ['10.1.1.2']
    metrics_path: /snmp
    params:
      module: [if_mib]
      target: ['10.1.1.2']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: sine-lab-snmp-exporter:9116

  - job_name: 'snmp_router2'
    static_configs:
      - targets: ['10.2.2.1']
    metrics_path: /snmp
    params:
      module: [if_mib]
      target: ['10.2.2.1']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: sine-lab-snmp-exporter:9116

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']